stages:
  - build
  #- release

build_job:
  stage: build
  image: $CI_REGISTRY/ballast-dev/insomnia:latest
  script:
    - go build insomnia.go
    - chmod +x insomnia
  artifacts:
    paths:
      - insomnia
    expire_in: 1 week
  only:
    - main

      #release_job:
      #  stage: release
      #  script:
      #    - echo "Releasing insomnia"
      #  dependencies:
      #    - build_job
      #  only:
      #    - main
      #  release:
      #    name: "Release v1.0"
      #    tag_name: "v1.0"
      #    description: ""

